{application,cloak,
             [{applications,[kernel,stdlib,elixir,logger,crypto]},
              {description,"Elixir encryption library"},
              {modules,['Elixir.Cloak','Elixir.Cloak.Cipher',
                        'Elixir.Cloak.Ciphers.AES.CTR',
                        'Elixir.Cloak.Ciphers.AES.GCM',
                        'Elixir.Cloak.Ciphers.Deprecated.AES.CTR',
                        'Elixir.Cloak.Ciphers.Deprecated.AES.GCM',
                        'Elixir.Cloak.Crypto','Elixir.Cloak.Crypto.Interface',
                        'Elixir.Cloak.InvalidConfig',
                        'Elixir.Cloak.MissingCipher',
                        'Elixir.Cloak.Tags.Decoder',
                        'Elixir.Cloak.Tags.Encoder','Elixir.Cloak.Vault']},
              {registered,[]},
              {vsn,"1.1.1"}]}.
